import { useEffect, useState } from 'react';
import { BarChart, Bar, XAxis, YAxis, Tooltip, ResponsiveContainer, CartesianGrid, LineChart, Line } from 'recharts';
const API='http://127.0.0.1:5000';
const money=n=>`₹${Number(n||0).toLocaleString('en-IN',{maximumFractionDigits:2})}`;
export default function Analytics({token}){
 const [data,setData]=useState(null),[error,setError]=useState(''),[loading,setLoading]=useState(true);
 useEffect(()=>{fetch(`${API}/api/analytics`,{headers:{Authorization:`Bearer ${token}`}}).then(async r=>{const d=await r.json();if(!r.ok)throw Error(d.error||'Unable to load analytics');setData(d)}).catch(e=>setError(e.message)).finally(()=>setLoading(false))},[token]);
 if(loading)return <p className="p-6 text-slate-500">Loading your shop analytics…</p>;
 if(error)return <div className="rounded-xl bg-red-50 p-4 text-red-700">{error}</div>;
 if(!data?.hasSalesData)return <div className="space-y-3"><h1 className="text-2xl font-bold">Retail Analytics</h1><div className="rounded-xl border bg-white p-6"><h2 className="font-semibold">No sales history yet</h2><p className="mt-2 text-sm text-slate-600">Charts and KPIs appear only after you import your shop's sales CSV from My Products & Approvals. No sample data is shown.</p></div></div>;
 const t=data.totals;
 return <div className="space-y-6"><div><h1 className="text-2xl font-bold">Retail Analytics</h1><p className="mt-1 text-sm text-slate-500">Calculated from this retailer account's imported sales and saved product costs.</p></div><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{[['Sales records',t.records],['Units sold',Number(t.units).toLocaleString('en-IN')],['Sales revenue',money(t.revenue)],['Gross profit estimate',money(t.gross_profit)]].map(([label,value])=><div key={label} className="rounded-xl border bg-white p-5"><p className="text-sm text-slate-500">{label}</p><p className="mt-2 text-2xl font-bold">{value}</p></div>)}</div><div className="grid gap-5 xl:grid-cols-2"><section className="rounded-xl border bg-white p-5"><h2 className="font-semibold">Monthly sales revenue</h2><div className="mt-4 h-72"><ResponsiveContainer width="100%" height="100%"><LineChart data={data.monthly}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="period"/><YAxis/><Tooltip formatter={v=>money(v)}/><Line dataKey="revenue" name="Revenue"/></LineChart></ResponsiveContainer></div></section><section className="rounded-xl border bg-white p-5"><h2 className="font-semibold">Units sold by category</h2><div className="mt-4 h-72"><ResponsiveContainer width="100%" height="100%"><BarChart data={data.categories}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="name"/><YAxis/><Tooltip/><Bar dataKey="units" name="Units sold"/></BarChart></ResponsiveContainer></div></section></div><section className="rounded-xl border bg-white p-5"><h2 className="font-semibold">Top products by revenue</h2><div className="mt-4 overflow-x-auto"><table className="w-full text-sm"><thead><tr className="border-b text-left text-slate-500"><th className="p-3">SKU</th><th className="p-3">Product</th><th className="p-3">Units</th><th className="p-3">Avg. sale price</th><th className="p-3">Revenue</th></tr></thead><tbody>{data.topProducts.map(p=><tr className="border-b" key={p.sku}><td className="p-3">{p.sku}</td><td className="p-3">{p.name}</td><td className="p-3">{Number(p.units).toLocaleString('en-IN')}</td><td className="p-3">{money(p.averagePrice)}</td><td className="p-3">{money(p.revenue)}</td></tr>)}</tbody></table></div></section><p className="text-xs text-slate-500">Gross profit is an estimate using the product's current saved unit cost, not historical cost-at-sale. Historical cost snapshots are not captured yet.</p></div>
}
