import { useEffect, useState } from 'react';
import { Package, Search } from 'lucide-react';
const API='http://127.0.0.1:5000';
const money=n=>`₹${Number(n||0).toLocaleString('en-IN')}`;
export default function Inventory({token}){
 const [items,setItems]=useState([]),[search,setSearch]=useState(''),[error,setError]=useState(''),[loading,setLoading]=useState(true);
 useEffect(()=>{fetch(`${API}/api/inventory`,{headers:{Authorization:`Bearer ${token}`}}).then(async r=>{const d=await r.json();if(!r.ok)throw Error(d.error||'Unable to load inventory');setItems(d)}).catch(e=>setError(e.message)).finally(()=>setLoading(false))},[token]);
 const filtered=items.filter(p=>`${p.name} ${p.sku} ${p.category}`.toLowerCase().includes(search.toLowerCase()));
 const stock=items.reduce((a,p)=>a+Number(p.inventory||0),0),low=items.filter(p=>Number(p.inventory)<=5).length;
 return <div className="space-y-6"><div><h1 className="text-2xl font-bold">Inventory Intelligence</h1><p className="mt-1 text-sm text-slate-500">Live stock and sales summaries from your shop's saved records. Low-stock threshold is currently 5 units.</p></div>{error&&<div className="rounded-xl bg-red-50 p-3 text-red-700">{error}</div>}{loading?<p>Loading your inventory…</p>:<><div className="grid gap-4 sm:grid-cols-3"><Kpi label="Products" value={items.length}/><Kpi label="Total stock units" value={stock.toLocaleString('en-IN')}/><Kpi label="Low / out of stock" value={low}/></div>{items.length===0?<div className="rounded-xl border bg-white p-6"><h2 className="font-semibold">No products in this shop yet</h2><p className="mt-2 text-sm text-slate-600">Add products or import your product CSV from My Products & Approvals. Sample inventory is not used.</p></div>:<section className="rounded-xl border bg-white p-5"><div className="relative mb-4 max-w-sm"><Search className="absolute left-3 top-3 text-slate-400" size={16}/><input className="w-full rounded-lg border py-2 pl-9 pr-3" placeholder="Search SKU, product, category" value={search} onChange={e=>setSearch(e.target.value)}/></div><div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr className="border-b text-left text-slate-500"><th className="p-3">SKU / Product</th><th className="p-3">Category</th><th className="p-3">Current price</th><th className="p-3">Unit cost</th><th className="p-3">Stock</th><th className="p-3">Units sold</th><th className="p-3">Sales revenue</th></tr></thead><tbody>{filtered.map(p=><tr className="border-b" key={p.id}><td className="p-3"><b>{p.sku}</b><div>{p.name}</div></td><td className="p-3">{p.category}</td><td className="p-3">{money(p.currentPrice)}</td><td className="p-3">{money(p.unitCost)}</td><td className="p-3"><span className={Number(p.inventory)<=5?'font-semibold text-red-600':''}>{p.inventory}</span></td><td className="p-3">{Number(p.soldUnits||0).toLocaleString('en-IN')}</td><td className="p-3">{money(p.salesRevenue)}</td></tr>)}</tbody></table></div>{filtered.length===0&&<p className="p-6 text-center text-slate-500">No matching products.</p>}</section>}</>}</div>
}
function Kpi({label,value}){return <div className="rounded-xl border bg-white p-5"><Package size={20} className="text-blue-600"/><p className="mt-3 text-sm text-slate-500">{label}</p><p className="mt-1 text-2xl font-bold">{value}</p></div>}
