import { useEffect, useMemo, useState } from 'react';
import { FlaskConical, ArrowRight, Loader2 } from 'lucide-react';
const API='http://127.0.0.1:5000';
export default function WhatIfAnalysis({ token }){
 const [catalog,setCatalog]=useState({categories:[],productsByCategory:{}}); const [category,setCategory]=useState(''); const [product,setProduct]=useState(null);
 const [currentPrice,setCurrentPrice]=useState(0); const [scenarioPrice,setScenarioPrice]=useState(0); const [inventory,setInventory]=useState(0); const [discount,setDiscount]=useState(10); const [promotion,setPromotion]=useState('None'); const [region,setRegion]=useState(''); const [customerType,setCustomerType]=useState('');
 const [result,setResult]=useState(null); const [loading,setLoading]=useState(false); const [error,setError]=useState('');
 useEffect(()=>{fetch(`${API}/api/catalog`, {headers:{Authorization:`Bearer ${token}`}}).then(r=>r.json()).then(d=>{setCatalog(d);setCategory(d.categories?.[0]||'')}).catch(()=>setError('Backend is not running. Start Flask on port 5000.'))},[token]);
 const ps=useMemo(()=>catalog.productsByCategory?.[category]||[],[catalog,category]);
 useEffect(()=>{const p=ps[0];if(p){setProduct(p);setCurrentPrice(p.currentPrice);setScenarioPrice(p.currentPrice);setInventory(p.inventory||0);setRegion(p.region||'');setResult(null)}},[category,ps]);
 const chooseProduct=e=>{const p=ps.find(x=>String(x.id)===e.target.value);if(p){setProduct(p);setCurrentPrice(p.currentPrice);setScenarioPrice(p.currentPrice);setInventory(p.inventory||0);setRegion(p.region||'');setResult(null)}};
 const run=async()=>{setLoading(true);setError('');setResult(null);try{const r=await fetch(`${API}/api/what-if`,{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${token}`},body:JSON.stringify({category,productId:product.id,product:product.name,scenarioPrice,discount,promotion,region,customerType})});const d=await r.json();if(!r.ok)throw Error(d.error||'Simulation failed');setResult(d)}catch(e){setError(e.message)}finally{setLoading(false)}};
 return <div className="space-y-6"><div><h1 className="text-2xl font-bold text-slate-900">What-If Analysis</h1><p className="mt-1 text-sm text-slate-500">Compare prices using this shop's imported product and sales history. Results are unavailable until sales history exists for the selected product.</p></div>
 <div className="rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="grid gap-5 p-6 md:grid-cols-2 lg:grid-cols-3">
 <Field label="Category"><select className="input" value={category} onChange={e=>setCategory(e.target.value)}>{catalog.categories.map(c=><option key={c}>{c}</option>)}</select></Field>
 <Field label="Product"><select className="input" value={product?.name||''} onChange={chooseProduct}>{ps.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></Field>
 <Field label="Current Price (₹)"><input className="input" type="number" value={currentPrice} readOnly/></Field>
 <Field label="What-If Price (₹)"><input className="input" type="number" value={scenarioPrice} onChange={e=>setScenarioPrice(Number(e.target.value))}/></Field>
 <Field label="Inventory (from your product record)"><input className="input" type="number" value={inventory} readOnly/></Field>
 <Field label="Discount (%)"><input className="input" type="number" value={discount} onChange={e=>setDiscount(Number(e.target.value))}/></Field>
 <Field label="Promotion"><select className="input" value={promotion} onChange={e=>setPromotion(e.target.value)}><option>None</option><option>Black Friday</option><option>Bundle Offer</option><option>Free Shipping</option><option>FOODIE10</option></select></Field>
 <Field label="Region"><input className="input" value={region} onChange={e=>setRegion(e.target.value)}/></Field>
 <Field label="Customer Type"><input className="input" value={customerType} onChange={e=>setCustomerType(e.target.value)}/></Field>
 </div><div className="border-t border-slate-200 p-6"><button onClick={run} disabled={loading||!product} className="flex items-center gap-2 rounded-xl bg-purple-600 px-6 py-3 text-sm font-semibold text-white hover:bg-purple-700 disabled:opacity-60">{loading?<Loader2 size={18} className="animate-spin"/>:<FlaskConical size={18}/>} {loading?'Calculating from shop sales history…':'Run What-If Simulation'} <ArrowRight size={17}/></button>{error&&<div className="mt-4 rounded-xl bg-red-50 p-3 text-sm text-red-700">{error}</div>}</div></div>
 {result&&<div className="grid gap-5 lg:grid-cols-2"><Compare title="Current Price" data={result.current}/><Compare title="What-If Price" data={result.scenario}/><div className="lg:col-span-2 rounded-2xl border border-purple-100 bg-purple-50 p-5"><div className="grid gap-4 md:grid-cols-3"><Metric label="Demand Change" value={result.demandChange}/><Metric label="Revenue Change" value={`₹${result.revenueChange.toLocaleString('en-IN')}`}/><Metric label="Profit Change" value={`₹${result.profitChange.toLocaleString('en-IN')}`}/></div><p className="mt-4 text-sm text-purple-800"><b>{result.category}</b> → <b>{result.product}</b> → <b>{result.model}</b>. Predictions are estimates; validate against your own sales history before making business decisions.</p></div></div>}
 <style>{`.input{width:100%;border:1px solid #cbd5e1;border-radius:.75rem;background:white;padding:.75rem 1rem;font-size:.875rem;outline:none}.input:focus{border-color:#7c3aed}`}</style></div>
}
function Field({label,children}){return <div><label className="mb-2 block text-sm font-medium text-slate-700">{label}</label>{children}</div>}
function Compare({title,data}){return <div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h3 className="font-semibold text-slate-900">{title}</h3><div className="mt-4 grid grid-cols-3 gap-3"><Metric label="Demand" value={data.predictedDemand}/><Metric label="Revenue" value={`₹${data.expectedRevenue.toLocaleString('en-IN')}`}/><Metric label="Profit" value={`₹${data.expectedProfit.toLocaleString('en-IN')}`}/></div></div>}
function Metric({label,value}){return <div><p className="text-xs text-slate-500">{label}</p><p className="mt-1 font-bold text-slate-900">{value}</p></div>}
